### ISSUE TITLE
UnboundLocalError: local variable 'script_x_test' referenced before assignment

### ISSUE THREAD

**Issue by jamesmishra** [45Drives/tools#18] opened 2021-04-11 05:45 UTC
I receive this Python traceback when running dmap.

```
Traceback (most recent call last):
  File "/home/james/tools/src/fakeroot/opt/45drives/tools/dmap", line 490, in <module>
    main()
  File "/home/james/tools/src/fakeroot/opt/45drives/tools/dmap", line 452, in main
    if not verify_vdev():
  File "/home/james/tools/src/fakeroot/opt/45drives/tools/dmap", line 171, in verify_vdev
    if not script_x_test:
UnboundLocalError: local variable 'script_x_test' referenced before assignment
```

I am calling dmap as the root user and without any arguments. I receive the same error with both Python 3.6 and 3.8. If I insert `script_x_test = None` at the beginning of the function, but then references to other variables end up triggering UnboundLocalErrors.

Is there a way around this?

**Comment by markdhooper** [comment] 2021-08-31 12:13
dmap assumes that it is running from `/opt/45drives/tools/ `. You could move the 45drives directory to /opt/. Or try installing the 45drives-tools package (Ubuntu, Centos7, or Rocky Linux). I think that this workaround will work for you after that. The problem is that dmap is looking for another python script `/opt/45drives/tools/server_identifier` which revealed a bug in the dmap code to me. So thanks for pointing it out.

**Comment by markdhooper** [comment] 2021-09-23 13:51
This has been resolved in subsequent releases of 45drives-tools. Which is available on our [official repo](https://repo.45drives.com).

You can setup this repo using a handy [setup script](https://repo.45drives.com/setup.html)

Then use your package manager to install 45drives-tools.

**Closed as completed by markdhooper** 2021-09-23 13:51 UTC
